# Install the app dependencies in a full Node docker image
FROM node:10
  
WORKDIR "/cibcdh"

# Install OS updates 
RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get clean \
 && echo 'Finished installing dependencies'

# Copy package.json and package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm install --production

# Copy the dependencies into a Slim Node docker image
FROM node:10-slim
  
WORKDIR "/cibcdh"

# Install OS updates 
RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get clean \
 && echo 'Finished installing dependencies'

# Install app dependencies
COPY --from=0 /cibcdh/node_modules /cibcdh/node_modules
COPY . /app

ENV NODE_ENV production
ENV PORT 8000

USER node

EXPOSE 8000
CMD ["npm", "start"]
